### ISSUE TITLE
【依頼】chat-space挙動確認

### ISSUE THREAD

**Issue by iemoto** [iemoto/chat-space#17]
#IPアドレス
18.177.59.33

**Comment by kohei-isoda** [comment]
ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

**◯ メッセージ投稿日時が日本時間になっていない**
[![Screenshot from Gyazo](https://gyazo.com/f243b80f0460b3e4a99df35dc8450655/raw)](https://gyazo.com/f243b80f0460b3e4a99df35dc8450655)

`※ 本来であれば16時33分になっていなければいけません。`

逆に言えば上記以外は完璧でした、どれも綺麗に作られて驚きました！
修正し次第、以下のChatSpace完了報告フォームを再度提出お願いします！
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by iemoto** [comment]
修正しました！

**Comment by kohei-isoda** [comment]
再提出ありがとうございます！
確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
修正お疲れ様でした、おめでとうございます！

**Comment by iemoto** [comment]
ありがとうございました。
